# src = pipe.c
# obj = pipe.o
opt = -g -c

all: 
	gcc -fdiagnostics-color=always -g /root/ClassSystem/expe3/expe3.c -o /root/ClassSystem/expe3/expe3 -std=c99 -lreadline -lncurses /usr/lib64/libreadline.so
clean:
	rm tpipe  pipe *.o